sudo: required
services:
    - docker

before_install:
    - docker build -t kc/docker-react-test -f Dockerfile.dev .

script:
    - docker run -e CI=true kc/docker-react-test npm run test

deploy:
    provider: elasticbeanstack
    region: "us-west-2"
    app: "docker-react-test"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-west-2-180383066833"
    bucket_path: "docker-react-test"
    on:
       branch: master
    access\_key\_id: "$aws_access-key"
    secret\_access\_key: 
       secure: "$aws_secret_key"

