sudo: required
services:
    - docker

before_install:
    - docker build -t kc/docker-react-test -f Dockerfile.dev .

script:
    - docker run -e CI=true kc/docker-react-test npm run test

deploy:
    provider: elasticbeanstalck
    region: "us-west-2"
    app: "docker-react-test"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-west-2-180383066833"
    bucket_path: "docker-react-test"
    on:
       branch: master
    access_key_id: "$accesskeyaws"
    secret_access_key: 
       secure: "$secretkeyaws"

